#!/usr/bin/env ruby
require 'rake'
require_relative '../config'

if File.exists?("rack.pid")
  pid = File.open("rack.pid"){|f| f.read}.to_i
  Process.kill(:INT, pid)
  sleep 1 # FIXME
end

sh "git pull"
sh "bundle install"
sh "bundle exec rackup -s thin -o #{CONFIG['SERVER_HOST']} -p #{CONFIG['SERVER_PORT']} -E production -D -P rack.pid"
